### ISSUE TITLE
Upgrading from 0.9.2 to 0.9.3 deletes admin group mapping

### ISSUE THREAD

**Issue by ktbartholomew** [ktbartholomew/saml-20-single-sign-on#12]
@phille97 I just spoke with a user who had this issue and (luckily) had SSO bypass enabled to fix it.

Prior to 0.9.3, the name of the administrator role was `admin`. Since 0.9.3, however, the name of the role is `administratror`. This mismatch is leaving users who upgrade to 0.9.3 or later with no admin users.

We should add a bit of upgrade logic (similar to https://github.com/ktbartholomew/saml-20-single-sign-on/blob/master/src/lib/classes/saml_settings.php#L382) to copy the value from the older `admin` role to `administrator` for a smooth upgrade transition.

**Comment by stephen-kainos** [comment]
@ktbartholomew i've been affected by this as well. All admins lost access. What's the best way to fix this?

**Comment by ktbartholomew** [comment]
@stephen-kainos short of cutting/shipping another version with the upgrade logic described above, you could uninstall and reinstall the plugin. When you set up the group mappings again, they'll get assigned to the right places. If you do this, you may want to save the certificate/key generated by the plugin to avoid having to reconfigure the certificate with your identity provider.

**Comment by phille97** [comment]
Hi @ktbartholomew ! I created a PR that should fix this.

Sorry that I couldn't get back to you until now, i've been kinda busy lately

**Comment by ktbartholomew** [comment]
Fixed w/ #13
