### ISSUE TITLE
Plugin page removes on wordpress.org

### ISSUE THREAD

**Issue by Fraifrai** [ktbartholomew/saml-20-single-sign-on#22]
Hi,

The plugin's homepage seems to have disappeared. Do you know why ??? https://wordpress.org/plugins/saml-20-single-sign-on/

The support page seems to be up : https://wordpress.org/support/plugin/saml-20-single-sign-on

Last question : is this plugin multi-site compliant ? I cannot configure it on sub-blogs.

thx in advance

**Comment by ktbartholomew** [comment]
See https://github.com/ktbartholomew/saml-20-single-sign-on/issues/20.

https://github.com/ktbartholomew/saml-20-single-sign-on/pull/21 Should bring with it much more reliable multi-site behavior.
